export enum EmployeeRole {
  ADMIN = 'ADMIN',
  LECTURER = 'LECTURER',
  DEAN = 'DEAN',
  COORDINATOR = 'COORDINATOR',
  PROGRAM_COMMITTEE_MEMBER = 'PROGRAM_COMMITTEE_MEMBER',
  DIPLOMA_SECTION_MEMBER = 'DIPLOMA_SECTION_MEMBER',
}
